name: CompileLaTeX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # check "real-document" section: https://github.com/dante-ev/latex-action
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Pdflatex presentation \#1
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: presentation.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      # - name: bibtex presentation
      #   uses: dante-ev/latex-action@2021-A
      #   with:
      #     root_file: presentation.aux
      #     compiler: bibtex
      #     args: 
      - name: Pdflatex presentation \#2
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: presentation.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: Pdflatex presentation \#3
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: presentation.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: Release file .pdf
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "presentation.pdf"
          tags: false
          draft: false
      - name: Delete older release
        uses: dev-drprasad/delete-older-releases@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          keep_latest: 3
